# Generated by Django 6.0 on 2026-01-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='name',
            new_name='foodname',
        ),
    ]
