# Generated by Django 6.0 on 2026-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_fooditems_description_alter_fooditems_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
