# Generated by Django 6.0 on 2026-01-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_name_fooditems_foodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
