# Generated by Django 6.0 on 2026-01-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
