# Generated by Django 6.0 on 2026-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly')], max_length=100),
        ),
    ]
