# Generated by Django 6.0 on 2026-01-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_fooditems_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Catogeries',
            field=models.CharField(choices=[('BURGER', 'Burger'), ('DOSA', 'Dosa'), ('MEALS', 'Meals'), ('Meat', 'Meat'), ('BIRIYANI', 'Biriyani')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
