# Generated by Django 6.0 on 2026-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_fooditems_catogeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Catogeries',
            field=models.CharField(choices=[('BURGER', 'Burger'), ('DOSA', 'Dosa'), ('MEALS', 'Meals'), ('BIRIYANI', 'Biriyani'), ('CURRY', 'curry'), ('FISH', 'Fish')], max_length=100),
        ),
    ]
