# Generated by Django 6.0 on 2026-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_fooditems_catogeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Catogeries',
            field=models.CharField(choices=[('BURGER', 'Burger'), ('DOSA', 'Dosa'), ('MEALS', 'Meals'), ('BIRIYANI', 'Biriyani'), ('CURRY', 'curry'), ('FISH', 'Fish'), ('PIZZA', 'pizza'), ('ICE CREAM', 'ice cream'), ('JUICE', 'juice'), ('PANIPURI', 'Panipuri'), ('GRIllED CHICKEN', 'grilled chicken')], max_length=100),
        ),
    ]
