# Generated by Django 6.0 on 2026-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_fooditems_catogeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Catogeries',
            field=models.CharField(choices=[('BURGER', 'Burger'), ('DOSA', 'Dosa'), ('MEALS', 'Meals'), ('BIRIYANI', 'Biriyani'), ('CURRY', 'curry'), ('FISH', 'Fish'), ('PIZZA', 'pizza'), ('ICE_CREAM', 'ice_cream'), ('JUICE', 'juice'), ('PANIPURI', 'Panipuri'), ('GRIllED_CHICKEN', 'grilled_chicken')], max_length=100),
        ),
    ]
