# Generated by Django 6.0 on 2026-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY')], max_length=100),
        ),
    ]
