# Generated by Django 6.0 on 2026-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly')], max_length=100),
        ),
    ]
