# Generated by Django 6.0 on 2026-01-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_fooditems_catogeries'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=100)),
                ('base_img', models.ImageField(blank=True, null=True, upload_to='base/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('sauce_img', models.ImageField(blank=True, null=True, upload_to='sauce/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('topping_img', models.ImageField(blank=True, null=True, upload_to='topping/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
    ]
