# Generated by Django 6.0 on 2026-03-05 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_basetype_sauce_size_topping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='Catogeries',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='foodimg',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='name',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='food_img',
            field=models.ImageField(default=1, upload_to='food_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='foodname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('food_img', models.ImageField(upload_to='food_images/')),
                ('catogery', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
