# Generated by Django 6.0 on 2026-03-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_remove_fooditems_catogeries_remove_fooditems_foodimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='foodname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
