# Generated by Django 6.0 on 2026-01-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam')], max_length=100),
        ),
    ]
