# Generated by Django 6.0 on 2026-01-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_alter_fooditems_catogery_basetype_sauce_size_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='foodimg/')),
            ],
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('DOSA', 'dosa'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
