# Generated by Django 6.0 on 2026-01-23 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_cart_alter_fooditems_catogery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='foodname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rating',
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
