# Generated by Django 6.0 on 2026-01-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_remove_cart_food_img_remove_cart_foodname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='foodname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
