# Generated by Django 6.0 on 2026-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0021_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='foodname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
