# Generated by Django 6.0 on 2026-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0025_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
