# Generated by Django 6.0 on 2026-01-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0026_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
