# Generated by Django 6.0 on 2026-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0027_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
