# Generated by Django 6.0 on 2026-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0031_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
