# Generated by Django 6.0 on 2026-01-29 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0032_remove_cart_user_alter_cart_catogery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
