# Generated by Django 6.0 on 2026-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0033_cart_user_alter_cart_catogery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
