# Generated by Django 6.0 on 2026-01-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0034_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
