# Generated by Django 6.0 on 2026-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0035_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
