# Generated by Django 6.0 on 2026-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0036_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('IDLY', 'Idly'), ('Poori', 'POORI'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
