# Generated by Django 6.0 on 2026-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0038_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('DOSA', 'dosa'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
