# Generated by Django 6.0 on 2026-02-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0039_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
