# Generated by Django 6.0 on 2026-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0040_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('Pongal', 'PONGAL'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
