# Generated by Django 6.0 on 2026-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0042_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('Briyani', 'BRIYANI'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('Chickennoodles', 'CHICKENOODLES'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
