# Generated by Django 6.0 on 2026-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0043_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('CHICKENRICE', 'Chickenrice'), ('Chickennoodles', 'CHICKENOODLES'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('IDLY', 'Idly'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('IDIYAPPAM', 'Idiyappam'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
