# Generated by Django 6.0 on 2026-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0045_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('Paroota', 'PAROOTA'), ('Chickenrice', 'CHICKENRICE'), ('CHICKENOODLES', 'Chickennoodles'), ('Chappati', 'CHAPPAATI'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('Poori', 'POORI'), ('Pongal', 'PONGAL'), ('Idiyappam', 'IDIYAPPAM'), ('KICHIDI', 'kichidi'), ('UPUMA', 'upuma')], max_length=100),
        ),
    ]
