# Generated by Django 6.0 on 2026-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0047_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('BRIYANI', 'Briyani'), ('PAROOTA', 'Paroota'), ('CHICKENRICE', 'Chickenrice'), ('CHICKENOODLES', 'Chickennoodles'), ('CHAPPAATI', 'Chappati'), ('dosa', 'DOSA'), ('Idly', 'IDLY'), ('POORI', 'Poori'), ('PONGAL', 'Pongal'), ('Idiyappam', 'IDIYAPPAM'), ('kichidi', 'KICHIDI'), ('upuma', 'UPUMA')], max_length=100),
        ),
    ]
