# Generated by Django 6.0 on 2026-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0048_alter_cart_catogery_alter_fooditems_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catogery',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food_img',
            field=models.ImageField(default=1, upload_to='food_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='foodname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='food_img',
            field=models.ImageField(default=1, upload_to='food_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='foodname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.FloatField(),
        ),
    ]
