# Generated by Django 6.0 on 2026-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0050_remove_cart_catogery_remove_cart_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='base',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sauces',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='catogery',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='food_img',
            field=models.ImageField(default=1, upload_to='food_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='foodname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.IntegerField(),
        ),
    ]
