# Generated by Django 6.0 on 2026-02-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0052_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
