# Generated by Django 6.0 on 2026-03-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_alter_fooditems_foodname'),
        ('foods', '0054_remove_cart_catogery_remove_cart_description_and_more'),
    ]

    operations = [
    ]
