# Generated by Django 6.0 on 2026-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('NORMALUSER', 'Normaluser'), ('VENDER', 'Vender')], default='user', max_length=100),
        ),
    ]
